local_resinos:
  app-name: myapp
  build-triggers:
    - Dockerfile: bbb20c8e2ee493e8f2f8ae185881657aa5dc73b9f32bd9ce046804f3202809b1
  environment:
    - TEXT_FREQ=1
    - TWILIO_NUMBER='+17208097549'
    - CONTACT_NUMBER='+17203334371'
    - TZ=America/New_York
    - TWILIO_ACCT_SID=AC418d083117870727526b01a66b6ffc5c
    - TWILIO_AUTH_TOKEN=2a569c979685138c2c59a469c6629b47
    - ALERT_LOCAL=F
ignore:
  - .git
  - node_modules/
destination: /usr/src/app
